# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: No-Project CI/CD

on:
  push:
    branches: ['master']
  pull_request:
    types: ['closed']
    branches: ['master']
    
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install
    - run: npx ng build
    - run: npx ng test --watch false --browsers ChromeHeadless
    - run: chmod u+x deploy.sh; ./deploy.sh;
