# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: No-Project CI/CD

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]
    branches: [master]
    
jobs:
  build-test-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: |
        echo 'Install Packages'
        npm install
    - run: |
        echo 'Build Project'
        npx ng build
    - run: |
        echo 'Test Cases & Coverage'
        npx ng test --watch false --browsers ChromeHeadless
    - run: |
        echo 'Deploy Build'
        cd dist
        zip -r no-project.zip no-project
        curl -X POST -F 'build=@no-project.zip' -H 'Password: ${{secrets.PASSWORD}}' http://akshaynile.pythonanywhere.com/no-project
        rm no-project.zip
        cd ..
